-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 20:03:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema orderup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orderup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orderup` DEFAULT CHARACTER SET utf8 ;
USE `orderup` ;

-- -----------------------------------------------------
-- Table `orderup`.`Orderables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`Orderables` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `price` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderup`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`Employees` (
  `ID` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `salary` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderup`.`TableArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`TableArea` (
  `ID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderup`.`Tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`Tables` (
  `ID` INT NOT NULL,
  `TableArea_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `TableArea_ID`),
  INDEX `fk_Tables_TableArea1_idx` (`TableArea_ID` ASC) ,
  CONSTRAINT `fk_Tables_TableArea1`
    FOREIGN KEY (`TableArea_ID`)
    REFERENCES `orderup`.`TableArea` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderup`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`Orders` (
  `ID` INT NOT NULL,
  `Tables_ID` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`, `Tables_ID`),
  INDEX `fk_Orders_Tables1_idx` (`Tables_ID` ASC) ,
  CONSTRAINT `fk_Orders_Tables1`
    FOREIGN KEY (`Tables_ID`)
    REFERENCES `orderup`.`Tables` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderup`.`Manages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`Manages` (
  `TableArea_ID` INT NOT NULL,
  `Employees_ID` INT NOT NULL,
  INDEX `fk_TableArea_has_Employees_Employees1_idx` (`Employees_ID` ASC) ,
  INDEX `fk_TableArea_has_Employees_TableArea1_idx` (`TableArea_ID` ASC) ,
  CONSTRAINT `fk_TableArea_has_Employees_TableArea1`
    FOREIGN KEY (`TableArea_ID`)
    REFERENCES `orderup`.`TableArea` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TableArea_has_Employees_Employees1`
    FOREIGN KEY (`Employees_ID`)
    REFERENCES `orderup`.`Employees` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderup`.`Contains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`Contains` (
  `Orders_ID` INT NOT NULL,
  `Orderables_ID` INT NOT NULL,
  INDEX `fk_Orders_has_Orderables_Orderables1_idx` (`Orderables_ID` ASC) ,
  INDEX `fk_Orders_has_Orderables_Orders1_idx` (`Orders_ID` ASC) ,
  CONSTRAINT `fk_Orders_has_Orderables_Orders1`
    FOREIGN KEY (`Orders_ID`)
    REFERENCES `orderup`.`Orders` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Orderables_Orderables1`
    FOREIGN KEY (`Orderables_ID`)
    REFERENCES `orderup`.`Orderables` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orderup`.`Prepares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orderup`.`Prepares` (
  `Orders_ID` INT NOT NULL,
  `Employees_ID` INT NOT NULL,
  INDEX `fk_Orders_has_Employees_Employees1_idx` (`Employees_ID` ASC) ,
  INDEX `fk_Orders_has_Employees_Orders1_idx` (`Orders_ID` ASC) ,
  CONSTRAINT `fk_Orders_has_Employees_Orders1`
    FOREIGN KEY (`Orders_ID`)
    REFERENCES `orderup`.`Orders` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_has_Employees_Employees1`
    FOREIGN KEY (`Employees_ID`)
    REFERENCES `orderup`.`Employees` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
